### ISSUE TITLE
Бесконечная загрузка 

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Yurichz/W-Hole#26]
Запросы упали и все время пишет Loading... в идеале нужно показать сообщение об ошибке или хоть написать "упс... что-то пошло не так"
![Screenshot 2022-07-14 at 19 38 53](https://user-images.githubusercontent.com/59687966/179033468-54ab537b-8511-4866-9089-bc0047196190.png)

**Comment by Yurichz** [comment]
Ой, у меня почему-то в начале ключа 0 убрался 😅, сейчас исправлю.

**Comment by Yurichz** [comment]
Всё исправил, и добавил сообщение на кнопке при ошибке.
